planner_configs:
  BKPIECE_BOOKSHELF_SMALL:
    type: geometric::BKPIECE
    range: 0.4209
  BKPIECE_BOOKSHELF_TALL:
    type: geometric::BKPIECE
    range: 0.4727
  BKPIECE_BOOKSHELF_THIN:
    type: geometric::BKPIECE
    range: 0.4635
  BKPIECE_BOX:
    type: geometric::BKPIECE
    range: 0.9723
  BKPIECE_CAGE:
    type: geometric::BKPIECE
    range: 0.3644
  BKPIECE_KITCHEN:
    type: geometric::BKPIECE
    range: 0.5914
  BKPIECE_TABLE_PICK:
    type: geometric::BKPIECE
    range: 0.9257
  BKPIECE_DEFAULT:
    type: geometric::BKPIECE
  RRTConnect_BOOKSHELF_SMALL:
    type: geometric::RRTConnect
    range: 0.2142
  RRTConnect_BOOKSHELF_TALL:
    type: geometric::RRTConnect
    range: 0.7611
  RRTConnect_BOOKSHELF_THIN:
    type: geometric::RRTConnect
    range: 0.5080
  RRTConnect_BOX:
    type: geometric::RRTConnect
    range: 4.2123
  RRTConnect_CAGE:
    type: geometric::RRTConnect
    range: 0.2167
  RRTConnect_KITCHEN:
    type: geometric::RRTConnect
    range: 4.2357
  RRTConnect_TABLE_PICK:
    type: geometric::RRTConnect
    range: 2.7199
  RRTConnect_DEFAULT:
    type: geometric::RRTConnect
  BiEST_BOOKSHELF_SMALL:
    type: geometric::BiEST
    range: 1.149
  BiEST_BOOKSHELF_TALL:
    type: geometric::BiEST
    range: 1.499 
  BiEST_BOOKSHELF_THIN:
    type: geometric::BiEST
    range: 1.205 
  BiEST_BOX:
    type: geometric::BiEST
    range: 14.157 
  BiEST_CAGE:
    type: geometric::BiEST
    range: 1.4018 
  BiEST_KITCHEN:
    type: geometric::BiEST
    range: 14.248
  BiEST_TABLE_PICK:
    type: geometric::BiEST
    range: 14.116
  BiEST_DEFAULT:
    type: geometric::BiEST
  BiEST_0_05:
    type: geometric::BiEST
    range: 0.05 
  BiEST_0_25:
    type: geometric::BiEST
    range: 0.25 
  BiEST_0_50:
    type: geometric::BiEST
    range: 0.50 
  BiEST_0_75:
    type: geometric::BiEST
    range: 0.75 
  BiEST_1_00:
    type: geometric::BiEST
    range: 1.00 
  BiEST_1_25:
    type: geometric::BiEST
    range: 1.25 
  BiEST_1_50:
    type: geometric::BiEST
    range: 1.50 
  BiEST_1_75:
    type: geometric::BiEST
    range: 1.75 
  BiEST_2_00:
    type: geometric::BiEST
    range: 2.00 
  BiEST_2_25:
    type: geometric::BiEST
    range: 2.25 
  BiEST_2_50:
    type: geometric::BiEST
    range: 2.50 
  BiEST_2_75:
    type: geometric::BiEST
    range: 2.75 
  BiEST_3_00:
    type: geometric::BiEST
    range: 3.00 
  BiEST_3_25:
    type: geometric::BiEST
    range: 3.25 
  BiEST_3_50:
    type: geometric::BiEST
    range: 3.50 
  BiEST_3_75:
    type: geometric::BiEST
    range: 3.75 
  BiEST_4_00:
    type: geometric::BiEST
    range: 4.00 
  BiEST_4_25:
    type: geometric::BiEST
    range: 4.25 
  BiEST_4_50:
    type: geometric::BiEST
    range: 4.50 
  BiEST_4_75:
    type: geometric::BiEST
    range: 4.75 
  BiEST_5_00:
    type: geometric::BiEST
    range: 5.00 
  BiEST_5_25:
    type: geometric::BiEST
    range: 5.25 
  BiEST_5_50:
    type: geometric::BiEST
    range: 5.50 
  BiEST_5_75:
    type: geometric::BiEST
    range: 5.75 
  BiEST_6_00:
    type: geometric::BiEST
    range: 6.00 
  BiEST_6_25:
    type: geometric::BiEST
    range: 6.25 
  BiEST_6_50:
    type: geometric::BiEST
    range: 6.50 
  BiEST_6_75:
    type: geometric::BiEST
    range: 6.75 
  BiEST_7_00:
    type: geometric::BiEST
    range: 7.00 
  BKPIECE_0_05:
    type: geometric::BKPIECE
    range: 0.05 
  BKPIECE_0_25:
    type: geometric::BKPIECE
    range: 0.25 
  BKPIECE_0_50:
    type: geometric::BKPIECE
    range: 0.50 
  BKPIECE_0_75:
    type: geometric::BKPIECE
    range: 0.75 
  BKPIECE_1_00:
    type: geometric::BKPIECE
    range: 1.00 
  BKPIECE_1_25:
    type: geometric::BKPIECE
    range: 1.25 
  BKPIECE_1_50:
    type: geometric::BKPIECE
    range: 1.50 
  BKPIECE_1_75:
    type: geometric::BKPIECE
    range: 1.75 
  BKPIECE_2_00:
    type: geometric::BKPIECE
    range: 2.00 
  BKPIECE_2_25:
    type: geometric::BKPIECE
    range: 2.25 
  BKPIECE_2_50:
    type: geometric::BKPIECE
    range: 2.50 
  BKPIECE_2_75:
    type: geometric::BKPIECE
    range: 2.75 
  BKPIECE_3_00:
    type: geometric::BKPIECE
    range: 3.00 
  BKPIECE_3_25:
    type: geometric::BKPIECE
    range: 3.25 
  BKPIECE_3_50:
    type: geometric::BKPIECE
    range: 3.50 
  BKPIECE_3_75:
    type: geometric::BKPIECE
    range: 3.75 
  BKPIECE_4_00:
    type: geometric::BKPIECE
    range: 4.00 
  BKPIECE_4_25:
    type: geometric::BKPIECE
    range: 4.25 
  BKPIECE_4_50:
    type: geometric::BKPIECE
    range: 4.50 
  BKPIECE_4_75:
    type: geometric::BKPIECE
    range: 4.75 
  BKPIECE_5_00:
    type: geometric::BKPIECE
    range: 5.00 
  BKPIECE_5_25:
    type: geometric::BKPIECE
    range: 5.25 
  BKPIECE_5_50:
    type: geometric::BKPIECE
    range: 5.50 
  BKPIECE_5_75:
    type: geometric::BKPIECE
    range: 5.75 
  BKPIECE_6_00:
    type: geometric::BKPIECE
    range: 6.00 
  BKPIECE_6_25:
    type: geometric::BKPIECE
    range: 6.25 
  BKPIECE_6_50:
    type: geometric::BKPIECE
    range: 6.50 
  BKPIECE_6_75:
    type: geometric::BKPIECE
    range: 6.75 
  BKPIECE_7_00:
    type: geometric::BKPIECE
    range: 7.00 
  RRTConnect_0_05:
    type: geometric::RRTConnect
    range: 0.05 
  RRTConnect_0_25:
    type: geometric::RRTConnect
    range: 0.25 
  RRTConnect_0_50:
    type: geometric::RRTConnect
    range: 0.50 
  RRTConnect_0_75:
    type: geometric::RRTConnect
    range: 0.75 
  RRTConnect_1_00:
    type: geometric::RRTConnect
    range: 1.00 
  RRTConnect_1_25:
    type: geometric::RRTConnect
    range: 1.25 
  RRTConnect_1_50:
    type: geometric::RRTConnect
    range: 1.50 
  RRTConnect_1_75:
    type: geometric::RRTConnect
    range: 1.75 
  RRTConnect_2_00:
    type: geometric::RRTConnect
    range: 2.00 
  RRTConnect_2_25:
    type: geometric::RRTConnect
    range: 2.25 
  RRTConnect_2_50:
    type: geometric::RRTConnect
    range: 2.50 
  RRTConnect_2_75:
    type: geometric::RRTConnect
    range: 2.75 
  RRTConnect_3_00:
    type: geometric::RRTConnect
    range: 3.00 
  RRTConnect_3_25:
    type: geometric::RRTConnect
    range: 3.25 
  RRTConnect_3_50:
    type: geometric::RRTConnect
    range: 3.50 
  RRTConnect_3_75:
    type: geometric::RRTConnect
    range: 3.75 
  RRTConnect_4_00:
    type: geometric::RRTConnect
    range: 4.00 
  RRTConnect_4_25:
    type: geometric::RRTConnect
    range: 4.25 
  RRTConnect_4_50:
    type: geometric::RRTConnect
    range: 4.50 
  RRTConnect_4_75:
    type: geometric::RRTConnect
    range: 4.75 
  RRTConnect_5_00:
    type: geometric::RRTConnect
    range: 5.00 
  RRTConnect_5_25:
    type: geometric::RRTConnect
    range: 5.25 
  RRTConnect_5_50:
    type: geometric::RRTConnect
    range: 5.50 
  RRTConnect_5_75:
    type: geometric::RRTConnect
    range: 5.75 
  RRTConnect_6_00:
    type: geometric::RRTConnect
    range: 6.00 
  RRTConnect_6_25:
    type: geometric::RRTConnect
    range: 6.25 
  RRTConnect_6_50:
    type: geometric::RRTConnect
    range: 6.50 
  RRTConnect_6_75:
    type: geometric::RRTConnect
    range: 6.75 
  RRTConnect_7_00:
    type: geometric::RRTConnect
    range: 7.00 
arm_with_torso:
  planner_configs:
    - BKPIECE_BOOKSHELF_SMALL
    - BKPIECE_BOOKSHELF_TALL
    - BKPIECE_BOOKSHELF_THIN
    - BKPIECE_BOX
    - BKPIECE_CAGE
    - BKPIECE_KITCHEN
    - BKPIECE_TABLE_PICK
    - BKPIECE_DEFAULT
    - RRTConnect_BOOKSHELF_SMALL
    - RRTConnect_BOOKSHELF_TALL
    - RRTConnect_BOOKSHELF_THIN
    - RRTConnect_BOX
    - RRTConnect_CAGE
    - RRTConnect_KITCHEN
    - RRTConnect_TABLE_PICK
    - RRTConnect_DEFAULT
    - BiEST_BOOKSHELF_SMALL
    - BiEST_BOOKSHELF_TALL
    - BiEST_BOOKSHELF_THIN
    - BiEST_BOX
    - BiEST_CAGE
    - BiEST_KITCHEN
    - BiEST_TABLE_PICK
    - BiEST_DEFAULT
    - RRTConnect_0_05
    - RRTConnect_0_25
    - RRTConnect_0_50
    - RRTConnect_0_75
    - RRTConnect_1_00
    - RRTConnect_1_25
    - RRTConnect_1_50
    - RRTConnect_1_75
    - RRTConnect_2_00
    - RRTConnect_2_25
    - RRTConnect_2_50
    - RRTConnect_2_75
    - RRTConnect_3_00
    - RRTConnect_3_25
    - RRTConnect_3_50
    - RRTConnect_3_75
    - RRTConnect_4_00
    - RRTConnect_4_25
    - RRTConnect_4_50
    - RRTConnect_4_75
    - RRTConnect_5_00
    - RRTConnect_5_25
    - RRTConnect_5_50
    - RRTConnect_5_75
    - RRTConnect_6_00
    - RRTConnect_6_25
    - RRTConnect_6_50
    - RRTConnect_6_75
    - RRTConnect_7_00
    - BiEST_0_05
    - BiEST_0_25
    - BiEST_0_50
    - BiEST_0_75
    - BiEST_1_00
    - BiEST_1_25
    - BiEST_1_50
    - BiEST_1_75
    - BiEST_2_00
    - BiEST_2_25
    - BiEST_2_50
    - BiEST_2_75
    - BiEST_3_00
    - BiEST_3_25
    - BiEST_3_50
    - BiEST_3_75
    - BiEST_4_00
    - BiEST_4_25
    - BiEST_4_50
    - BiEST_4_75
    - BiEST_5_00
    - BiEST_5_25
    - BiEST_5_50
    - BiEST_5_75
    - BiEST_6_00
    - BiEST_6_25
    - BiEST_6_50
    - BiEST_6_75
    - BiEST_7_00
    - BKPIECE_0_05
    - BKPIECE_0_25
    - BKPIECE_0_50
    - BKPIECE_0_75
    - BKPIECE_1_00
    - BKPIECE_1_25
    - BKPIECE_1_50
    - BKPIECE_1_75
    - BKPIECE_2_00
    - BKPIECE_2_25
    - BKPIECE_2_50
    - BKPIECE_2_75
    - BKPIECE_3_00
    - BKPIECE_3_25
    - BKPIECE_3_50
    - BKPIECE_3_75
    - BKPIECE_4_00
    - BKPIECE_4_25
    - BKPIECE_4_50
    - BKPIECE_4_75
    - BKPIECE_5_00
    - BKPIECE_5_25
    - BKPIECE_5_50
    - BKPIECE_5_75
    - BKPIECE_6_00
    - BKPIECE_6_25
    - BKPIECE_6_50
    - BKPIECE_6_75
    - BKPIECE_7_00
  projection_evaluator: joints(torso_lift_joint,shoulder_pan_joint)
  longest_valid_segment_fraction: 0.005
