start_queries:
  - objects: ["table_top"]
    tag: "Under"
    offset:
      position: [-0.5, 0.0, -0.3]
      orientation: [0, 0, 0, 1]
      position_tol: [0.0001, 0.0001, 0.0001]
      orientation_tol: [0.003, 0.003, 0.003]
    attached: "False"

goal_queries:
  - objects: ["Can1"]
    tag: "Front"
    offset:
      position: [0, -0.05, 0.08]
      orientation: [0.707, 0, 0.707, 0]
      position_tol: [0.0001, 0.0001, 0.0001]
      orientation_tol: [0.003, 0.003, 0.003]
    attached: "False"
