- names: ["World"]
  position: [0.1 , 0.1, 0.1]
  orientation: [0, 0, 1.57]
  type: "uniform"
- names: ["Can1"]
  position: [0.05 , 0.05, 0]
  orientation: [0 , 0, 0]
  type: "uniform"
- names: ["Object1", "Object2", "Object3", "Object4", "Object5", "Cube"]
  position: [0.1 , 0.1, 0]
  orientation: [0 , 0, 1.57]
  type: "uniform"

