world:
  collision_objects:
    - header:
        frame_id: base_link
      id: Can1
      primitives:
        - type: cylinder
          dimensions: [0.12, 0.03]
      primitive_poses:
        - position: [0.75, 0, 0.49]
          orientation: [0, 0, 0, 1]
    - header:
        frame_id: base_link
      id: table_leg_left_back
      primitives:
        - type: box
          dimensions: [0.05, 0.05, 0.7]
      primitive_poses:
        - position: [1.4, 0.75, 0.35]
          orientation: [0, 0, 0, 1]
    - header:
        frame_id: base_link
      id: table_leg_left_front
      primitives:
        - type: box
          dimensions: [0.05, 0.05, 0.7]
      primitive_poses:
        - position: [0.7, 0.75, 0.35]
          orientation: [0, 0, 0, 1]
    - header:
        frame_id: base_link
      id: table_leg_right_back
      primitives:
        - type: box
          dimensions: [0.05, 0.05, 0.7]
      primitive_poses:
        - position: [1.4, -0.75, 0.35]
          orientation: [0, 0, 0, 1]
    - header:
        frame_id: base_link
      id: table_leg_right_front
      primitives:
        - type: box
          dimensions: [0.05, 0.05, 0.7]
      primitive_poses:
        - position: [0.7, -0.75, 0.35]
          orientation: [0, 0, 0, 1]
    - header:
        frame_id: base_link
      id: table_top
      primitives:
        - type: box
          dimensions: [1, 1.5, 0.05]
      primitive_poses:
        - position: [1, 0, 0.4]
          orientation: [0, 0, 0, 1]
