start_queries:
  - objects: ["shelves"]
    tag: "ArmAboveShelfR"
    offset:
      position: [0.35, -0.2, 0.7]
      orientation: [0, 0, 0, 1]
      position_tol: [0.01, 0.01, 0.01]
      orientation_tol: [0.01, 0.01, 0.01]
    attached: "False"

  - objects: ["shelves"]
    tag: "ArmAboveShelfL"
    offset:
      position: [0.35, 0.2, 0.7]
      orientation: [0, 0, 0, 1]
      position_tol: [0.01, 0.01, 0.01]
      orientation_tol: [0.01, 0.01, 0.01]
    attached: "False"

goal_queries:
  - objects: ["shelves"]
    tag: "ArmBelowShelfR"
    offset:
      position: [0.35, -0.2, 0.25]
      orientation: [0, 0, 0, 1]
      position_tol: [0.01, 0.01, 0.01]
      orientation_tol: [0.01, 0.01, 0.01]
    attached: "False"

  - objects: ["shelves"]
    tag: "ArmBelowShelfL"
    offset:
      position: [0.35, 0.2, 0.25]
      orientation: [0, 0, 0, 1]
      position_tol: [0.01, 0.01, 0.01]
      orientation_tol: [0.01, 0.01, 0.01]
    attached: "False"
