start_queries:
  - objects: ["shelves"]
    tag: "ArmAboveShelf"
    offset:
      position: [0.55, 0.0, 0.7]
      orientation: [0, 0, 0, 1]
      position_tol: [0.01, 0.01, 0.01]
      orientation_tol: [0.01, 0.01, 0.01]
    attached: "False"

goal_queries:
  - objects: ["shelves"]
    tag: "ArmBelowShelf"
    offset:
      position: [0.55, 0.0, 0.25]
      orientation: [0, 0, 0, 1]
      position_tol: [0.01, 0.01, 0.01]
      orientation_tol: [0.01, 0.01, 0.01]
    attached: "False"

