world:
  collision_objects:
    - header:
        frame_id: base_link
      id: Can1
      primitives:
        - type: cylinder
          dimensions: [0.14, 0.03]
      primitive_poses:
        - position: [0.8, 0, 0.55]
          orientation: [0, 0, 0, 1]
    - header:
        frame_id: base_link
      id: base 
      primitives:
        - type: box
          dimensions: [0.7, 0.7, 0.04]
      primitive_poses:
        - position: [0.8, 0, 0.44]
          orientation: [0, 0, 0, 1]
    - header:
        frame_id: base_link
      id: side_left
      primitives:
        - type: box
          dimensions: [0.7, 0.04, 0.7]
      primitive_poses:
        - position: [0.8, -0.35, 0.8]
          orientation: [0, 0, 0, 1]
    - header:
        frame_id: base_link
      id: side_right
      primitives:
        - type: box
          dimensions: [0.7, 0.04, 0.7]
      primitive_poses:
        - position: [0.8, 0.35, 0.8]
          orientation: [0, 0, 0, 1]
    - header:
        frame_id: base_link
      id: side_front
      primitives:
        - type: box
          dimensions: [0.04, 0.7, 0.6]
      primitive_poses:
        - position: [0.45, 0, 0.7]
          orientation: [0, 0, 0, 1]
    - header:
        frame_id: base_link
      id: side_cap
      primitives:
        - type: box
          dimensions: [0.7, 0.7, 0.04]
      primitive_poses:
        - position: [0.9, 0, 1.35]
          orientation: [0, 0.383, 0, 0.924]
    - header:
        frame_id: base_link
      id: side_back
      primitives:
        - type: box
          dimensions: [0.04, 0.7, 0.7]
      primitive_poses:
        - position: [1.15, 0, 0.8]
          orientation: [0, 0, 0, 1]
