robot_description: package://motion_bench_maker/configs/robots/baxter.yaml
ompl_config: package://motion_bench_maker/configs/ompl/ompl_planning_baxter.yaml
scene: package://motion_bench_maker/configs/scenes/bookshelf/scene_small.yaml
queries: package://motion_bench_maker/configs/scenes/bookshelf/hard_queries_small.yaml
variation: package://motion_bench_maker/configs/scenes/bookshelf/variation_small.yaml
sensors: package://motion_bench_maker/configs/scenes/bookshelf/sensors_small.yaml
planning_group: left_arm
samples: 100
base_offset:
    position    : [0.4, 0, -0.7]
    orientation : [0, 0, 0 , 1]
ee_offset:
    position    : [0.0, 0, -0.25]
    orientation:  [0, -0.707, 0, 0.707]
