robot_description: package://motion_bench_maker/configs/robots/baxter.yaml
ompl_config: package://motion_bench_maker/configs/ompl/ompl_planning_baxter.yaml
scene: package://motion_bench_maker/configs/scenes/bookshelf/scene_thin.yaml
queries: package://motion_bench_maker/configs/scenes/bookshelf/hard_queries_thin.yaml
variation: package://motion_bench_maker/configs/scenes/bookshelf/variation_thin.yaml
sensors: package://motion_bench_maker/configs/scenes/bookshelf/sensors_thin.yaml
planning_group: left_arm 
samples: 100
base_offset:
    position    : [0.1, 0, -0.7]
    orientation : [0, 0, 0, 1]
ee_offset:
    position    : [0.0, 0, -0.25]
    orientation:  [0, -0.707, 0, 0.707]
