robot_description: package://motion_bench_maker/configs/robots/ur5.yaml
ompl_config: package://motion_bench_maker/configs/ompl/ompl_planning_ur5.yaml
scene: package://motion_bench_maker/configs/scenes/bookshelf/scene_tall.yaml
queries: package://motion_bench_maker/configs/scenes/bookshelf/easy_queries_tall.yaml
variation: package://motion_bench_maker/configs/scenes/bookshelf/variation_tall.yaml
sensors: package://motion_bench_maker/configs/scenes/bookshelf/sensors_tall.yaml
planning_group: manipulator
samples: 100
base_offset:
    position    : [0.1, 0.1, -0.9144]
    orientation : [0, 0, 0, 1]
ee_offset:
    position    : [0.0, 0, 0]
    orientation:  [0, 0, 0, 1]
