robot_description: package://motion_bench_maker/configs/robots/baxter.yaml
ompl_config: package://motion_bench_maker/configs/ompl/ompl_planning_baxter.yaml
scene: package://motion_bench_maker/configs/scenes/bookshelf/scene_tall.yaml
queries: package://motion_bench_maker/configs/scenes/bookshelf/easy_queries_tall.yaml
variation: package://motion_bench_maker/configs/scenes/bookshelf/variation_tall_medium.yaml
sensors: package://motion_bench_maker/configs/scenes/bookshelf/sensors_tall.yaml
planning_group: both_arms 
samples: 100
base_offset:
    position    : [0.5, 0, -1]
    orientation : [0, 0, 0 , 1]
ee_offset:
  - position    :  [0.0, 0, -0.25]
    orientation :  [0, -0.707, 0, 0.707]
    ee_tip:   "left_gripper"  
  - position    :  [0.0, 0, -0.25]
    orientation :  [0, -0.707, 0, 0.707]
    ee_tip :  "right_gripper"
ee_dependency: False
