robot_description: package://motion_bench_maker/configs/robots/baxter.yaml
ompl_config: package://motion_bench_maker/configs/ompl/ompl_planning_baxter.yaml
scene: package://motion_bench_maker/configs/scenes/box/scene_box.yaml
queries: package://motion_bench_maker/configs/scenes/box/hard_queries_box.yaml
variation: package://motion_bench_maker/configs/scenes/box/variation_box.yaml
sensors: package://motion_bench_maker/configs/scenes/box/sensors_box.yaml
planning_group: right_arm
samples: 100
base_offset:
    position    : [0.3, -0.2, -0.95]
    orientation : [0, 0, 0.707, -0.707]
ee_offset:
    position    : [0.0, 0, -0.15]
    orientation:  [0, -0.707, 0, 0.707]
