robot_description: package://motion_bench_maker/configs/robots/ur5.yaml
ompl_config: package://motion_bench_maker/configs/ompl/ompl_planning_ur5.yaml
scene: package://motion_bench_maker/configs/scenes/box/scene_box.yaml
queries: package://motion_bench_maker/configs/scenes/box/easy_queries_box.yaml
variation: package://motion_bench_maker/configs/scenes/box/variation_box.yaml
sensors: package://motion_bench_maker/configs/scenes/box/sensors_box.yaml
planning_group: manipulator
samples: 100
base_offset:
    position    : [0, 0, -1.1]
    orientation : [0, 0, 0, 1]
ee_offset:
    position    : [0.035, -0.045, 0.0]
    orientation:  [0, 0, 0, 1]
