robot_description: package://motion_bench_maker/configs/robots/panda.yaml
ompl_config: package://motion_bench_maker/configs/ompl/ompl_planning_panda.yaml
scene: package://motion_bench_maker/configs/scenes/cage/scene_cage.yaml
queries: package://motion_bench_maker/configs/scenes/cage/queries_cage.yaml
variation: package://motion_bench_maker/configs/scenes/cage/variation_cage.yaml
sensors: package://motion_bench_maker/configs/scenes/cage/sensors_cage.yaml
planning_group: panda_arm
samples: 100
base_offset:
    position    : [0, 0, -0.18]
    orientation : [0, 0, 0, 1]
ee_offset:
    position    : [0.13, -0.13, 0.11]
    orientation:  [0, 0, 0.924, 0.383]  
