robot_description: package://motion_bench_maker/configs/robots/baxter.yaml
ompl_config: package://motion_bench_maker/configs/ompl/ompl_planning_baxter.yaml
scene: package://motion_bench_maker/configs/scenes/kitchen/kitchen.urdf
queries: package://motion_bench_maker/configs/scenes/kitchen/hard_queries.yaml
variation: package://motion_bench_maker/configs/scenes/kitchen/variation.yaml
sensors: package://motion_bench_maker/configs/scenes/kitchen/sensors.yaml
planning_group: right_arm
samples: 100
base_offset:
    position    : [0.5, 0, -0.7]
    orientation : [0, 0, 0 , 1]
ee_offset:
    position    : [0, 0, -0.05]
    orientation:  [0, -0.707, 0, 0.707]
