robot_description: package://motion_bench_maker/configs/robots/ur5.yaml
ompl_config: package://motion_bench_maker/configs/ompl/ompl_planning_ur5.yaml
scene: package://motion_bench_maker/configs/scenes/kitchen/kitchen.urdf
queries: package://motion_bench_maker/configs/scenes/kitchen/hard_queries.yaml
variation: package://motion_bench_maker/configs/scenes/kitchen/variation.yaml
sensors: package://motion_bench_maker/configs/scenes/kitchen/sensors.yaml
planning_group: manipulator
samples: 100
base_offset:
    position    : [0, 0, 0.1]
    orientation : [0, 0, 0, 1]
ee_offset:
    position    : [0, -0.045, 0]
    orientation : [0, 0, 0, 1]
