robot_description: package://motion_bench_maker/configs/robots/shadowhand.yaml
ompl_config: package://motion_bench_maker/configs/ompl/ompl_planning.yaml
scene: package://motion_bench_maker/configs/scenes/pregrasp/metal.urdf
queries: package://motion_bench_maker/configs/scenes/pregrasp/queries_metal.yaml
variation: package://motion_bench_maker/configs/scenes/pregrasp/variation_metal.yaml
sensors: package://motion_bench_maker/configs/scenes/pregrasp/sensors_metal.yaml
planning_group: finger_ff
samples: 20
base_offset:
    position    : [0, 0, 0]
    orientation : [0, 0, 0, 1]
ee_offset:
    position    : [0, 0, 0]
    orientation:  [0, 0, 0, 1]
