robot_description: package://motion_bench_maker/configs/robots/shadowhand.yaml
ompl_config: package://motion_bench_maker/configs/ompl/ompl_planning_shadow.yaml
scene: package://motion_bench_maker/configs/scenes/table_bars/table_bars.urdf
queries: package://motion_bench_maker/configs/scenes/table_bars/single_arm_queries.yaml
variation: package://motion_bench_maker/configs/scenes/table_bars/variation.yaml
sensors: package://motion_bench_maker/configs/scenes/table_bars/sensors.yaml
planning_group: all_fingers 
samples: 100
base_offset:
    position    : [0.2, 0, 0]
    orientation : [0, 0, 0, 1]
ee_offset:
  - position    : [0, 0, 0]
    orientation : [0, 0, 0, 1]
    ee_tip: "ffdistal"
  - position    : [0.02, 0, 0]
    orientation : [0, 0, 0, 1]
    ee_tip: "mfdistal"
  - position    : [0.04, 0, 0]
    orientation : [0, 0, 0, 1]
    ee_tip: "rfdistal"
  - position    : [0.06, 0, 0]
    orientation : [0, 0, 0, 1]
    ee_tip: "lfdistal"
  - position    : [-0.02, -0.13, 0.02]
    orientation : [0.0, 0.0, 0.996, 0.087 ]
    ee_tip: "thdistal"
ee_dependency: True

