robot_description: package://motion_bench_maker/configs/robots/ur5.yaml
ompl_config: package://motion_bench_maker/configs/ompl/ompl_planning_ur5.yaml
scene: package://motion_bench_maker/configs/scenes/table/scene_table.yaml
queries: package://motion_bench_maker/configs/scenes/table/queries_under_pick_table.yaml
variation: package://motion_bench_maker/configs/scenes/table/variation_table.yaml
sensors: package://motion_bench_maker/configs/scenes/table/sensors_table.yaml
planning_group: manipulator
samples: 100
base_offset:
    position    : [0, 0, -0.45]
    orientation : [0, 0, 0, 1]
ee_offset:
    position    : [0, 0, 0]
    orientation : [0, 0, 0, 1]
