robot_description: package://motion_bench_maker/configs/robots/panda.yaml
ompl_config: package://motion_bench_maker/configs/ompl/ompl_planning_panda.yaml
scene: package://motion_bench_maker/configs/scenes/table_bars/table_bars.urdf
queries: package://motion_bench_maker/configs/scenes/table_bars/single_arm_queries.yaml
variation: package://motion_bench_maker/configs/scenes/table_bars/variation.yaml
sensors: package://motion_bench_maker/configs/scenes/table_bars/sensors.yaml
planning_group: panda_arm
samples: 100
base_offset:
    position    : [0.6, 0, -0.6]
    orientation : [0, 0, 0 , 1]
ee_offset:
    position    : [0.29, -0.29, 0.35] 
    orientation:  [-0.271, -0.653, -0.271, 0.653]
