urdf: package://robowflex_resources/panda/urdf/panda.urdf
srdf: package://robowflex_resources/panda/config/panda.srdf
kinematics: package://robowflex_resources/panda/config/kinematics.yaml
limits: package://robowflex_resources/panda/config/joint_limits.yaml
robot_state:
  joint_state:
    name: ["panda_finger_joint1", "panda_finger_joint2", "panda_joint1", "panda_joint2", "panda_joint3", "panda_joint4", "panda_joint5", "panda_joint6", "panda_joint7"]
    position: [0.065, 0.065, 0, -0.785, 0, -2.356, 0, 1.571, 0.785]
