# Yumi robot
urdf: "package://robowflex_resources/yumi/urdf/yumi.urdf"
srdf: "package://robowflex_resources/yumi/config/yumi.srdf"
limits: "package://robowflex_resources/yumi/config/joint_limits.yaml"
kinematics: "package://robowflex_resources/yumi/config/kinematics.yaml"

robot_state:
  joint_state:
    name: [yumi_joint_1_r, yumi_joint_2_r, yumi_joint_7_r, yumi_joint_3_r, yumi_joint_4_r, yumi_joint_5_r,yumi_joint_6_r, yumi_joint_1_l, yumi_joint_2_l, yumi_joint_7_l, yumi_joint_3_l, yumi_joint_4_l, yumi_joint_5_l, yumi_joint_6_l]
    position: [-0.8, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.8, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

