goal_queries:
  - objects: ["Can2","Can4","Can6","Can8","Can10"]
    tag: "Front"
    offset:
      position: [0, -0.08, 0.05]
      orientation: [0.707, 0, 0.707, 0]
      position_tol: [0.01, 0.01, 0.01]
      orientation_tol: [0.01, 0.01, 0.01]
    attached: "False"
