world:
  collision_objects:
    - header:
        frame_id: base_link
      id: Can1
      primitives:
        - type: cylinder
          dimensions: [0.14, 0.03]
      primitive_poses:
        - position: [1.1, 0.25, 0.44]
          orientation: [0, 0, 0, 1]
    - header:
        frame_id: base_link
      id: Can2
      primitives:
        - type: cylinder
          dimensions: [0.14, 0.03]
      primitive_poses:
        - position: [0.8, 0.25, 0.44]
          orientation: [0, 0, 0, 1]
    - header:
        frame_id: base_link
      id: Can3
      primitives:
        - type: cylinder
          dimensions: [0.14, 0.03]
      primitive_poses:
        - position: [1.1, -0.25, 0.69]
          orientation: [0, 0, 0, 1]
    - header:
        frame_id: base_link
      id: Can4
      primitives:
        - type: cylinder
          dimensions: [0.14, 0.03]
      primitive_poses:
        - position: [0.8, -0.25, 0.69]
          orientation: [0, 0, 0, 1]
    - header:
        frame_id: base_link
      id: Can5
      primitives:
        - type: cylinder
          dimensions: [0.14, 0.03]
      primitive_poses:
        - position: [1.1, 0.25, 0.94]
          orientation: [0, 0, 0, 1]
    - header:
        frame_id: base_link
      id: Can6
      primitives:
        - type: cylinder
          dimensions: [0.14, 0.03]
      primitive_poses:
        - position: [0.8, 0.25, 0.94]
          orientation: [0, 0, 0, 1]
    - header:
        frame_id: base_link
      id: Can7
      primitives:
        - type: cylinder
          dimensions: [0.14, 0.03]
      primitive_poses:
        - position: [1.1, -0.25, 1.19]
          orientation: [0, 0, 0, 1]
    - header:
        frame_id: base_link
      id: Can8
      primitives:
        - type: cylinder
          dimensions: [0.14, 0.03]
      primitive_poses:
        - position: [0.8, -0.25, 1.19]
          orientation: [0, 0, 0, 1]
    - header:
        frame_id: base_link
      id: Can9
      primitives:
        - type: cylinder
          dimensions: [0.14, 0.03]
      primitive_poses:
        - position: [1.1, 0.25, 1.44]
          orientation: [0, 0, 0, 1]
    - header:
        frame_id: base_link
      id: Can10
      primitives:
        - type: cylinder
          dimensions: [0.14, 0.03]
      primitive_poses:
        - position: [0.8, 0.25, 1.44]
          orientation: [0, 0, 0, 1]
    - header:
        frame_id: base_link
      id: shelf_bottom
      primitives:
        - type: box
          dimensions: [0.62, 1, 0.04]
      primitive_poses:
        - position: [1.0, 0.0, 0.35]
          orientation: [0, 0, 0, 1]
    - header:
       frame_id: base_link
      id: shelf_middle_bottom
      primitives:
        - type: box
          dimensions: [0.62, 1, 0.04]
      primitive_poses:
        - position: [1.0, 0, 0.60]
          orientation: [0, 0, 0, 1]
    - header:
       frame_id: base_link
      id: shelf_middle
      primitives:
        - type: box
          dimensions: [0.62, 1, 0.04]
      primitive_poses:
        - position: [1.0, 0, 0.85]
          orientation: [0, 0, 0, 1]
    - header:
        frame_id: base_link
      id: shelf_middle_top
      primitives:
        - type: box
          dimensions: [0.62, 1, 0.04]
      primitive_poses:
        - position: [1, 0, 1.10]
          orientation: [0, 0, 0, 1]
    - header:
        frame_id: base_link
      id: shelf_top
      primitives:
        - type: box
          dimensions: [0.62, 1, 0.04]
      primitive_poses:
        - position: [1, 0, 1.35]
          orientation: [0, 0, 0, 1]
    - header:
        frame_id: base_link
      id: shelf_vert
      primitives:
        - type: box
          dimensions: [0.62, 0.04, 1.4]
      primitive_poses:
        - position: [1, 0, 0.9]
          orientation: [0, 0, 0, 1]
    - header:
        frame_id: base_link
      id: shelf_top_top
      primitives:
        - type: box
          dimensions: [0.62, 1, 0.04]
      primitive_poses:
        - position: [1, 0, 1.6]
          orientation: [0, 0, 0, 1]

    - header:
        frame_id: base_link
      id: leg_fr
      primitives:
        - type: box
          dimensions: [0.04, 0.04, 1.64]
      primitive_poses:
        - position: [0.7, 0.5, 0.82]
          orientation: [0, 0, 0, 1]
    - header:
        frame_id: base_link
      id: leg_fl
      primitives:
        - type: box
          dimensions: [0.04, 0.04, 1.64]
      primitive_poses:
        - position: [0.7, -0.5, 0.82]
          orientation: [0, 0, 0, 1]
    - header:
        frame_id: base_link
      id: leg_br
      primitives:
        - type: box
          dimensions: [0.04, 0.04, 1.64]
      primitive_poses:
        - position: [1.3, 0.5, 0.82]
          orientation: [0, 0, 0, 1]
    - header:
        frame_id: base_link
      id: leg_bl
      primitives:
        - type: box
          dimensions: [0.04, 0.04, 1.64]
      primitive_poses:
        - position: [1.3, -0.5, 0.82]
          orientation: [0, 0, 0, 1]
