world:
  collision_objects:
    - header:
        frame_id: base_link
      id: Can1
      primitives:
        - type: cylinder
          dimensions: [0.14, 0.03]
      primitive_poses:
        - position: [0.9, 0, 1.38]
          orientation: [0, 0, 0, 1]
    - header:
        frame_id: base_link
      id: Can2
      primitives:
        - type: cylinder
          dimensions: [0.14, 0.03]
      primitive_poses:
        - position: [0.7, 0, 1.38]
          orientation: [0, 0, 0, 1]
    - header:
        frame_id: base_link
      id: Can3
      primitives:
        - type: cylinder
          dimensions: [0.14, 0.03]
      primitive_poses:
        - position: [0.5, 0, 1.38]
          orientation: [0, 0, 0, 1]
    - header:
        frame_id: base_link
      id: Can4
      primitives:
        - type: cylinder
          dimensions: [0.14, 0.03]
      primitive_poses:
        - position: [0.9, 0, 0.78]
          orientation: [0, 0, 0, 1]
    - header:
        frame_id: base_link
      id: Can5
      primitives:
        - type: cylinder
          dimensions: [0.14, 0.03]
      primitive_poses:
        - position: [0.7, 0, 0.78]
          orientation: [0, 0, 0, 1]
    - header:
        frame_id: base_link
      id: Can6
      primitives:
        - type: cylinder
          dimensions: [0.14, 0.03]
      primitive_poses:
        - position: [0.5, 0, 0.78]
          orientation: [0, 0, 0, 1]
    - header:
        frame_id: base_link
      id: Can7
      primitives:
        - type: cylinder
          dimensions: [0.14, 0.03]
      primitive_poses:
        - position: [0.9, 0, 1.08]
          orientation: [0, 0, 0, 1]
    - header:
        frame_id: base_link
      id: Can8
      primitives:
        - type: cylinder
          dimensions: [0.14, 0.03]
      primitive_poses:
        - position: [0.7, 0, 1.08]
          orientation: [0, 0, 0, 1]
    - header:
        frame_id: base_link
      id: Can9
      primitives:
        - type: cylinder
          dimensions: [0.14, 0.03]
      primitive_poses:
        - position: [0.5, 0, 1.08]
          orientation: [0, 0, 0, 1]
    - header:
        frame_id: base_link
      id: shelf_bottom
      primitives:
        - type: box
          dimensions: [1.2, 1, 0.04]
      primitive_poses:
        - position: [1.0, 0, 0.7]
          orientation: [0, 0, 0, 1]
    - header:
       frame_id: base_link
      id: shelf_middle_bottom
      primitives:
        - type: box
          dimensions: [1.2, 1, 0.04]
      primitive_poses:
        - position: [1.0, 0, 1.0]
          orientation: [0, 0, 0, 1]
    - header:
       frame_id: base_link
      id: shelf_middle_top
      primitives:
        - type: box
          dimensions: [1.2, 1, 0.04]
      primitive_poses:
        - position: [1.0, 0, 1.3]
          orientation: [0, 0, 0, 1]
    - header:
        frame_id: base_link
      id: shelf_top
      primitives:
        - type: box
          dimensions: [1.2, 1, 0.04]
      primitive_poses:
        - position: [1, 0, 1.6]
          orientation: [0, 0, 0, 1]
    - header:
        frame_id: base_link
      id: side_left
      primitives:
        - type: box
          dimensions: [1.3, 0.04, 1.64]
      primitive_poses:
        - position: [1, -0.5, 0.82]
          orientation: [0, 0, 0, 1]
    - header:
        frame_id: base_link
      id: side_right
      primitives:
        - type: box
          dimensions: [1.3, 0.04, 1.64]
      primitive_poses:
        - position: [1, 0.5, 0.82]
          orientation: [0, 0, 0, 1]
