camera_config: package://motion_bench_maker/configs/sensors/camera.yaml
look_objects:
    - name: "shelf_bottom" 
      position: [0.0, -0.25, 0.2]
    - name: "shelf_middle_bottom" 
      position: [0.0, -0.25, 0.2]
    - name: "shelf_middle_top" 
      position: [0.0, -0.25, 0.2]
    - name: "shelf_bottom" 
      position: [0.0, 0.25, 0.2]
    - name: "shelf_middle_bottom" 
      position: [0.0, 0.25, 0.2]
    - name: "shelf_middle_top" 
      position: [0.0, 0.25, 0.2]


cam_points:
    - [0.0, 0.0, 0.2]
    - [0.0, 0.0, 0.4]
    - [0.0, 0.0, 0.6]
    - [0.0, 0.0, 0.8]
    - [0.0, 0.0, 1.0]
    - [0.0, 0.0, 1.2]
    - [0.0, 0.0, 1.4]

resolution: 0.02
