camera_config: package://motion_bench_maker/configs/sensors/camera.yaml
look_objects:
    - name: "shelf_bottom" 
      position: [0.0, 0.0, 0.2]
    - name: "side_left" 
      position: [-0.6, 0.0, 0.0]
    - name: "side_right" 
      position: [-0.6, 0.0, 0.0]
cam_points:
    - [0.0, 0.0, 0.6]
    - [0.0, 0.0, 0.7]
    - [0.0, 0.0, 0.8]
    - [0.0, 0.0, 0.9]
    - [0.0, 0.0, 1.0]
    - [0.0, 0.0, 1.1]
    - [0.0, 0.0, 1.2]
    - [0.0, 0.0, 1.3]
    - [0.0, 0.0, 1.4]

resolution: 0.02
