start_queries:
  - objects: ["cupboard"]
    tag: "FrontHard"
    offset:
      position: [0.6, 0.0, 1.5]
      orientation: [0, 0, 0, 1]
      position_tol: [0.1, 0.1, 0.1]
      orientation_tol: [0.01, 0.01, 0.01]
    attached: "False"
  - objects: ["cupboard"]
    tag: "FrontEasy"
    offset:
      position: [0.4, 0.0, 1.5]
      orientation: [0, 0, 0, 1]
      position_tol: [0.1, 0.1, 0.1]
      orientation_tol: [0.01, 0.01, 0.01]
    attached: "False"
goal_queries:
  - objects: ["kitchen_counter"]
    tag: "FrontHard"
    offset:
      position: [0.4, -0.5, 0.6]
      orientation: [0, 0, 0, 1]
      position_tol: [0.1, 0.1, 0.1]
      orientation_tol: [0.01, 0.01, 0.01]
    attached: "False"
  - objects: ["kitchen_counter"]
    tag: "FrontEasy"
    offset:
      position: [0.2, -0.5, 0.6]
      orientation: [0, 0, 0, 1]
      position_tol: [0.1, 0.1, 0.1]
      orientation_tol: [0.01, 0.01, 0.01]
    attached: "False"
