camera_config: package://motion_bench_maker/configs/sensors/camera.yaml
look_objects:
    - name: "cupboard" 
      position: [1, 0.5, 1]
    - name: "cupboard" 
      position: [1, 0.5, 1.5]
    - name: "cupboard" 
      position: [1, 0.5, 2]
    - name: "cupboard" 
      position: [1, -0.5, 0.3]
    - name: "cupboard" 
      position: [1, -0.5, 1.5]
    - name: "cupboard" 
      position: [1, -0.5, 2]
cam_points:
    - [-0.5, 0.0, 0.3]
    - [-0.5, 0.0, 1.0]
    - [-0.5, 0.0, 1.5]
    - [-0.5, 0.0, 2.0]
    - [-0.5, 0.0, 2.5]
    - [0.5, 0.0, 0.3]
    - [0.5, 0.0, 1.0]
    - [0.5, 0.0, 1.5]
    - [0.5, 0.0, 2.0]
    - [0.5, 0.0, 2.5]
    - [-0.5, -0.5, 0.3]
    - [-0.5, -0.5, 1.0]
    - [-0.5, -0.5, 1.3]
    - [-0.5, -0.5, 2.0]
    - [-0.5, -0.5, 2.5]
    - [0.5, -0.5, 0.3]
    - [0.5, -0.5, 1.0]
    - [0.5, -0.5, 1.5]
    - [0.5, -0.5, 2.0]
    - [0.5, -0.5, 2.5]



resolution: 0.02
